# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20171030_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='choice',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'false'), (1, 'true')], default=0, verbose_name='是否选中'),
        ),
    ]
