# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20171030_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InputRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=512, verbose_name='答案')),
            ],
        ),
        migrations.RemoveField(
            model_name='textarea',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='choicebox',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='inputbox',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='inputbox',
            name='survey',
        ),
        migrations.AddField(
            model_name='inputbox',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'text'), (2, 'text-area')], default=1, verbose_name='填空题类型'),
        ),
        migrations.AddField(
            model_name='survey',
            name='choice_boxes',
            field=models.ManyToManyField(to='survey.ChoiceBox', verbose_name='选择题'),
        ),
        migrations.AddField(
            model_name='survey',
            name='input_boxes',
            field=models.ManyToManyField(to='survey.InputBox', verbose_name='填空题'),
        ),
        migrations.AlterField(
            model_name='choicebox',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '单选'), (2, '多选')], default=1, verbose_name='选择题类型'),
        ),
        migrations.DeleteModel(
            name='TextArea',
        ),
        migrations.AddField(
            model_name='inputrecord',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.InputBox', verbose_name='问题'),
        ),
        migrations.AddField(
            model_name='inputrecord',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey', verbose_name='问卷'),
        ),
        migrations.AddField(
            model_name='inputrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.UserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='choicerecord',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Choice'),
        ),
        migrations.AddField(
            model_name='choicerecord',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.ChoiceBox', verbose_name='问题'),
        ),
        migrations.AddField(
            model_name='choicerecord',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey', verbose_name='问卷'),
        ),
        migrations.AddField(
            model_name='choicerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.UserInfo', verbose_name='用户'),
        ),
    ]
