# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20171031_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='班级名称')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_list', models.ManyToManyField(to='survey.ClassList', verbose_name='以报班级')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.UserInfo', verbose_name='学生姓名')),
            ],
        ),
    ]
