# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_classlist_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='class_list',
            field=models.ManyToManyField(to='survey.ClassList', verbose_name='所属班级'),
        ),
    ]
