# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_survey_class_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Student', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='inputrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Student', verbose_name='用户'),
        ),
    ]
