# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20171101_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='class_list',
        ),
        migrations.AddField(
            model_name='survey',
            name='items',
            field=models.ManyToManyField(to='survey.SurveyItem', verbose_name='题目'),
        ),
    ]
