# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20171102_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='survey_item',
            field=models.ManyToManyField(blank=True, null=True, to='survey.SurveyItem', verbose_name='所属题目'),
        ),
    ]
