# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20171102_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyitem',
            name='choices',
            field=models.ManyToManyField(to='survey.Choice', verbose_name='选项'),
        ),
    ]
