# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20171102_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroombooklist',
            name='for_who',
        ),
        migrations.AddField(
            model_name='meetingroombooklist',
            name='theme',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='会议主题'),
        ),
        migrations.AddField(
            model_name='meetingroombooklist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.UserInfo', verbose_name='预定人'),
        ),
    ]
